### ISSUE TITLE
Для названий к инпутам надо использовать тег label

### ISSUE THREAD

**Issue by uzarsalan** [InnaKhvan/Project-Sneackers#27]
Семантически верно использовать тег label для подписей к инпутам. Так браузер будет понимать связь. Можешь подробнее прочитать про этот тег

https://github.com/InnaKhvan/Project-Sneackers/blob/7028c106802ba56e41a6f9e39e9a808882d87b82/src/components/FilterForm/FilterBrand/index.js#L12

**Comment by InnaKhvan** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/116577321/236085361-6c624854-de52-4ea0-b2c8-12609eed6beb.png">
