### ISSUE TITLE
Вынести в mockData

### ISSUE THREAD

**Issue by uzarsalan** [InnaKhvan/Project-Sneackers#36]
@InnaKhvan слайды надо вынести в mockData

https://github.com/InnaKhvan/Project-Sneackers/blob/e8ce34ec3b72232d9bac4379b3685b708e2895fe/src/components/Slider/index.js#L8

**Comment by InnaKhvan** [comment]
16ecf6d16e1049ba618e85e490a9ecd8cb71995a
