### ISSUE TITLE
Неверная обработка события

### ISSUE THREAD

**Issue by uzarsalan** [InnaKhvan/Project-Sneackers#40]
В кнопке событие клика отлавливается по onClick

https://github.com/InnaKhvan/Project-Sneackers/blob/18d0d89d8c06a927fd933b2a1115780dbb1028df/src/components/Slider/index.js#L10

**Comment by InnaKhvan** [comment]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/116577321/236087738-da59e484-3a48-46a9-80c6-df3b3ca7fe88.png">
