### ISSUE TITLE
Нужно по максимуму использовать классы tailwindcss

### ISSUE THREAD

**Issue by uzarsalan** [InnaKhvan/Project-Sneackers#42]
Здесь и ниже нужно по максимуму использовать классы tailwindcss, а не писать стили с нуля

https://github.com/InnaKhvan/Project-Sneackers/blob/18d0d89d8c06a927fd933b2a1115780dbb1028df/src/components/ApplicationForm/index.js#L22

**Comment by InnaKhvan** [comment]
58f036b4c4c5a8ce0cf9adca278e3fa0d7f91b38
