### ISSUE TITLE
Пропс kind не используется

### ISSUE THREAD

**Issue by uzarsalan** [InnaKhvan/Project-Sneackers#43]
Пропс kind не используется нигде. В нем нет смысла

https://github.com/InnaKhvan/Project-Sneackers/blob/18d0d89d8c06a927fd933b2a1115780dbb1028df/src/components/InputElem/index.js#L4

**Comment by InnaKhvan** [comment]
c3fbc96c1cd4a80ae9d4796ca86aab3c425d26d1
